image: python:3.7.3
pipelines:
  default:
    - step:
        size: 2x   # double memory (8GB) for this step
        services:
          - docker
        caches:
          - docker
        script:
          - pip3 install pipenv
          - pipenv install -d
          - pipenv run python -m unittest discover tests/unit/ -v
          - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose up -d
          - docker-compose ps
          - pipenv run python create_schema.py
        #services:
          #- postgres

definitions:
  services:
    docker:
      memory: 7168