image: python:3.7.3
pipelines:
  default:
    - step:
        script:
          - pip3 install pipenv
          - pipenv install -d
          - pipenv run python -m unittest discover tests/unit/ -v
          - sudo apt-get update && sudo apt-get install -y postgresql-client
          - psql -c 'SELECT version();' -U root
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'python_test'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'root'