image: python:3.7.3
pipelines:
  default:
    - step:
        script:
          - pip3 install pipenv
          - pipenv install -d
          - pipenv run python -m unittest discover tests/unit/ -v
          # Install docker-compose via pip
          - pip3 install docker-compose
          - docker-compose up -d
          #- pipenv run python create_schema.py
        #services:
          #- postgres

#definitions:
  #services:
    #postgres:
      #image: postgres
      #variables:
        #POSTGRES_DB: 'python_test'
        #POSTGRES_USER: 'root'
        #POSTGRES_PASSWORD: 'root'